version: 2
jobs:
  build:
    working_directory: /go/src/github.com/segmentio/library-e2e-tester

    docker:
      - image: circleci/golang:1.12.1

    steps:
      - checkout

      - restore_cache:
          key: deps-v2-{{ checksum "go.sum" }}

      - run:
          name: Dependencies
          command: |
            make deps

      - run:
          name: Test
          command: |
            make test

      - save_cache:
          key: deps-v2-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
