version: 2
jobs:
  test:
    working_directory: /go/src/github.com/segmentio/library-e2e-tester

    docker:
      - image: circleci/golang:1.12.1

    steps:
      - checkout

      - restore_cache:
          key: deps-v2-{{ checksum "go.sum" }}

      - run:
          name: Dependencies
          command: |
            make deps

      - run:
          name: Test
          command: |
            make test

      - save_cache:
          key: deps-v2-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod

  dist:
    working_directory: /go/src/github.com/segmentio/library-e2e-tester
    
    docker:
      - image: circleci/golang:1.12.1
    
    steps:
      - checkout

      - attach_workspace: { at: . }

      - run:
          name: Install tools
          command: |
            make tools

      - run:
          name: Make distributables
          command: |
            make dist

      - persist_to_workspace:
          root: .
          paths: ['dist/*']

  publish:
    working_directory: /go/src/github.com/segmentio/library-e2e-tester

    docker:
      - image: circleci/golang:1.12.1

    steps:
      - checkout

      - attach_workspace: { at: . }

      - run:
          name: Publish
          command: |
            .buildscript/publish.sh

workflows:
  version: 2
  test-dist-publish:
    jobs:
      - test
      - dist:
          requires:
            - test
          # needed to ensure dist happens on tag events
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - dist
          filters:
            # never publish from a branch event
            branches:
              ignore: /.*/
            # release only on tag push events like vX[.Y.Z...][-whatever]
            tags:
              only: /[0-9]+(\.[0-9]+)*(-[a-zA-Z0-9-]+)?/
